### ISSUE TITLE
Playlists reset upon installing new mods

### ISSUE THREAD

**Issue by xJon** [Metalit/PlaylistManager#3]
This happens when syncing the mods. Was reported also by a few other people over Discord.
I'm not sure whether this is caused by PlaylistManager or not but it definitely affects it!
Using version `1.1.0`.

**Comment by L3Home** [comment]
I believe this bug is actually caused by BMBF. It does not pull your playlists "down" from the Quest when it syncs up to your computer, so when you Sync to Quest, it sends back your new changes and also its (very outdated) version of your playlists (usually empty or maybe with only a folder or two, like mine).

You can prevent this by doing the normal Sync to send changes to the Quest using BMBF but then on the first time opening the game to play, you should be prompted with a notice that external changes have been made to your playlist(s) AND asked whether you want to KEEP the changes. You want to select the option so that it does NOT keep those changes. The "changes" are the bad BMBF data. Thankfully, you can change mods and sync songs just fine without worrying, so long as you choose the correct option on that dialog.

Just as a side note, you can also back up your playlists as they are saved as plain text files on your Quest (you just have to connect and access its filesystem to get to them).

**Comment by xJon** [comment]
@L3Home Thank you for the detailed comment. I actually didn't have this happening in recent updates since even though I did the same things (only with backups), so I assume some workarounds were implemented to prevent this :)
