### ISSUE TITLE
[v1.25.1] Not all playlists showing when adding songs to another playlist, deleting cover images, or changing a cover image for a playlist in game (recordings of issue attached) 

### ISSUE THREAD

**Issue by ariJayne** [Metalit/PlaylistManager#4]
I posted this in the quest-help channel in discord but re-posting here since this does seem like a bug (and no one had an answer there) 

When I'm trying to move songs to other playlists it is only possible if I have the playlist set in one of the first 4-5 spots, if it's any farther in the list it doesn't show on the menu which makes it super inconvenient to quickly sort and move songs around. It also does this when deleting cover images in mod settings or  changing a cover image (whatever fits in the first section is all you'll be able to see)

https://user-images.githubusercontent.com/38627863/202935528-74d2062a-b105-4e26-8bf0-bdc71e78f87f.mp4

https://user-images.githubusercontent.com/38627863/202935531-d8558aeb-2a14-4e8a-8679-a24e14252afe.mp4

**Comment by Metalit** [comment]
Does this happen immediately after launching the game, or, say, only after playing a song?

**Comment by bostonlondon** [comment]
this happens to me too, happens no matter if I play a song or not.

**Comment by wisnoskij** [comment]
I have this exact issue. I think I was able to have 1-2 playlists in the second page, but when I added 1 more playlist it has been blank ever since. Not be able to do anyhitng about this with reloading palylists, rebooting, anything.

My Setup:
Quest 2
Beatsaber 1.25.1
BMBF 1.16.0
PlaylistManager v1.2.0

BSMG 1.16.0 seems to come with
SongLoader v0.10.9
PinkCore v1.8.3
PlaylistManager v1.2.0
SongDownloader v0.5.0
datakeeper v0.1.2
PlaylistCare v1.1.0
ModList v0.1.7
libquestui.so
libtinyxml2.so
libpaperlog.so
libcodegen.so
libbsml.so
libbeatsaber-hook_3_14_0.so
libcustom-types.so

This is just a brand new default BMBF install with some random songs syned to it.

**Comment by ariJayne** [comment]
@Metalit just tested and it does it at both the start of the game and after launch - tried in party and solo mode

**Comment by Metalit** [comment]
Strange issue. I'll look into it, thanks for the information

**Comment by Metalit** [comment]
Hard to say if I'll have a fix by 1.26 cores come out

**Comment by wisnoskij** [comment]
Looked at the code to see if I had any ideas. This probably wont be any help at all, but.
I don't think I can be a scrolling issue, as you can scroll back to the first page and that works.
So best guess is it is a `playlistCovers` issue. But I probably don't know what I am talking about.

https://github.com/Metalit/PlaylistManager/blob/f6b18211a7ac63b8aa5d548547b4cd81cce3581d/src/Types/LevelButtons.cpp#L374-L387

**Comment by Cynthia0608** [comment]
Is there any fix? I am experiencing the same issue and still don't see any trace of people saying it was fixed since then. I wish I could create playlists.

**Comment by Metalit** [comment]
So it turns out that the issue was caused by a change that BSML made. Maybe I should've thought to check that earlier since this issue did crop up around the version where BSML became core, but hindsight is 20/20. I'll release a fix and get the cores updated soon
